-- Add items to existing profiles or create your own to sell groups of items using alias commands
local profiles = {}

-- //sellnpc powder
profiles['powder'] = S{
    'prize powder',
    }

-- //sellnpc ore
profiles['ore'] = S{
    'iron ore',
    'copper ore',
    'tin ore',
    }

-- //sellnpc junk
profiles['junk'] = S{
    'chestnut',
    'san d\'Or. carrot',
    }

-- //sellnpc alljunk
profiles['alljunk'] = S{
    'san d\'Or. carrot',
    'Carrier Crab Carapace',
    'Kazham Peppers',
    'Mhaura Garlic',
    'Vanilla',
    'Sage',
    'Deathball',
    'Voay Sword -1',
    'Black Pepper',
    'Habaneros',
    'Bay Leaves',
    'Akaso', 
    'Potion', 
    'Gugru Tuna',  
    'Shall Shell', 
    'Dragon Fruit', 
    'Gigant Squid', 
    'Bluetail', 
    'Mackerel', 
    'Moorish Idol', 
    'Grimmonite', 
    'Millioncorn', 
    'Kukuru Bean', 
    'Puffball', 
    'Sunflower Seeds', 
    'Poison Flour', 
    'Blue Peas',  
    'Pugil Scales', 
    'Uragnite Shell', 
    'Ram Horn', 
    'Dragon Bone', 
    'Turtle Shell',  
    'Pebble',  
    'H.Q. Scp. Shell', 
    'Bone Chip', 
    'Meteorite', 
    'Elshimo Newt', 
    'Moat Carp', 
    'Copper Frog', 
    'Gavial Fish', 
    'Crescent Fish', 
    'Giant Catfish', 
    'Ca Cuong', 
    'Yorchete', 
    'Pamamas', 
    'Walnut',  
    'Grove Cuttings', 
    'Felicifruit', 
    'King Locust', 
    'Yagudo Cherry', 
    'Persikos', 
    'El. Pachira Fruit', 
    'Flax Flower', 
    'Skull Locust', 
    'Wijnruit', 
    'Red Rose', 
    'Watermelon', 
    'Red Moko Grass', 
    'Dark Bass', 
    'Gold Carp', 
    'Black Eel', 
    'Igneous Rock', 
    'Snapping Mole', 
    'Scorpion Shell', 
    'H.Q. Crab Shell', 
    'Scorpion Claw', 
    'Marguerite', 
    'Ulbukan Lobster', 
    'Yayinbaligi', 
    'Pipira', 
    'Ruddy Seema', 
    'Eggplant',  
    'Ulbuconut', 
    'Antlion Jaw',  
    'Voay Staff -1', 
    'Contortopus', 
    'Adoulinian Kelp', 
    'Black Prawn',  
    'Dragon Talon',  
    'Beetle Jaw', 
    'Crab Shell', 
    'Brass Loach', 
    'Rusty Bucket',  
    'Fresh Marjoram', 
    'Yagudo Drink', 
    'Cone Calamary', 
    'Zebra Eel', 
    'Quus', 
    'Bastore Bream', 
    'Titanictus', 
    'Tarutaru Rice', 
    'Rye Flour', 
    'Crayfish',  
    'Insect Wing', 
    'Rolanberry', 
    'Napa', 
    'Lesser Chigoe', 
    'Bloodblotch', 
    'Bat Fang',  
    'Fresh Mugwort', 
    'Pine Nuts', 
    'Crawler Cocoon', 
    'Acorn', 
    'Black Ghost', 
    'Faerie Apple', 
    'Red Terrapin', 
    'Barnacle', 
    'Little Worm', 
    'Chestnut', 
    'Coral Fungus', 
    'Bhefhel Marlin', 
    'Dwarf Remora', 
    'Win. Tea Leaves', 
    'Sheep Tooth', 
    'Blk. Tiger Fang',  
    'Bugard Tusk', 
    'Loc. Elutriator', 
    'Senroh Sardine',  
    'Green Rock', 
    'Giant Stinger', 
    'La Theine Cbg.', 
    'Pumpkin Pie', 
    'Nopales', 
    'San d\'Or. Flour', 
    'Dryad Root', 
    'Crawler Egg', 
    'Semolina', 
    'Tiny Goldfish', 
    'Woozyshroom', 
    'Matsya', 
    'Dragonfish', 
    'Flint Stone', 
    'Velkk Necklace', 
    'Velkk Mask', 
    'Matamata Shell',  
    'Moko Grass', 
    'Emperor Fish', 
    'Isleracea', 
    'Cactus Stems', 
    'Wivre Maul',
    'Raptor Skin',
    'Peiste Skin',
    'Slime Juice',
    'Infinity Core',
    'Acheron Shield',
    'Popoto',
    'Fish Bones',
    'Frost Turnip',
    'Ginger',
    'Graubg. Lettuce',
    'Wild Onion',
    'Dhalmel Pie',
    'Navarin',
    'Brass Harness',
    'Peace Cape',
    


    }




return profiles





