-- Add items to existing profiles or create your own to sell groups of items using alias commands
local profiles = {}

-- //sellnpc powder
profiles['powder'] = S{
    'prize powder',
    }

-- //sellnpc ore
profiles['ore'] = S{
    'iron ore',
    'copper ore',
    'tin ore',
    }

-- //sellnpc junk
profiles['junk'] = S{
    'chestnut',
    'san d\'Or. carrot',
    }

-- //sellnpc alljunk
profiles['alljunk'] = S{

    'Acheron Shield',
    'Acorn', 
    'Adoulinian Kelp', 
    'Aht Urhgan Dart',
    'Anchovy',
    'Antlion Jaw',  
    'Ardent Jadeite',
    'Barnacle', 
    'Bastore Bream', 
    'Bat Fang',  
    'Bay Leaves',
    'Beetle Jaw', 
    'Bhefhel Marlin', 
    'Black Eel', 
    'Black Ghost', 
    'Black Pepper',
    'Black Prawn',  
    'Blk. Tiger Fang',  
    'Bloodblotch', 
    'Blue Peas', 
    'Bluetail', 
    'Bone Chip', 
    'Brass Harness',
    'Brass Loach', 
    'Bugard Tusk', 
    'Bull\'s Diary',
    'Ca Cuong', 
    'Cactus Stems', 
    'Carrier Crab Carapace',
    'Chestnut', 
    'Colibri Beak',
    'Cone Calamary', 
    'Contortopus', 
    'Cook. Kit 15',
    'Copper Frog', 
    'Coral Fungus', 
    'Cornstarch',
    'Crab Shell', 
    'Crawler Cocoon', 
    'Crawler Egg', 
    'Crayfish',  
    'Crescent Fish', 
    'Dark Bass', 
    'Deathball',
    'Dhalmel Pie',
    'Dragon Bone', 
    'Dragon Fruit', 
    'Dragon Talon',  
    'Dragonfish', 
    'Dried Date',
    'Dried Date',
    'Dryad Root', 
    'Dwarf Remora', 
    'Eggplant',
    'Eggplant',  
    'El. Pachira Fruit', 
    'Elshimo Newt', 
    'Emperor Fish', 
    'Ether',
    'Faerie Apple',
    'Fish Bones',
    'Flax Flower', 
    'Flint Stone', 
    'Fresh Marjoram', 
    'Fresh Mugwort', 
    'Frost Turnip',
    'Garglle. Shank',
    'Gavial Fish', 
    'Giant Catfish', 
    'Giant Stinger', 
    'Gigant Squid', 
    'Ginger',
    'Gold Carp', 
    'Green Rock', 
    'Grimmonite', 
    'Grove Cuttings', 
    'Gugru Tuna',  
    'H.Q. Crab Shell', 
    'H.Q. Scp. Shell', 
    'Habaneros',
    'Hi-Ether +2',
    'Igneous Rock', 
    'Infinity Core',
    'Insect Wing', 
    'Isleracea', 
    'Kazham Peppers',
    'King Locust', 
    'King Truffle',
    'Kukuru Bean', 
    'La Theine Cbg.', 
    'Land Crab Meat',
    'Lesser Chigoe', 
    'Little Worm', 
    'Loc. Elutriator', 
    'Mackerel', 
    'Magnet Knife',
    'Marguerite', 
    'Matamata Shell',  
    'Matsya', 
    'Meteorite', 
    'Mhaura Garlic',
    'Millioncorn', 
    'Moat Carp', 
    'Moko Grass', 
    'Moorish Idol', 
    'Murex Spicule',
    'Mushrm. Locust',
    'Napa', 
    'Navarin',
    'Nopales', 
    'Pamamas', 
    'Peace Cape', 
    'Pebble Soup',
    'Pebble',  
    'Peeled Crayfish',
    'Peiste Skin',
    'Pine Nuts', 
    'Pipira', 
    'Poison Flour', 
    'Popoto',
    'Potion +1',
    'Potion', 
    'Pro-Ether',
    'Puffball', 
    'Pugil Scales', 
    'Pumpernickel',
    'Pumpkin Pie', 
    'Quus', 
    'R. Pickled R. Tail',
    'Ram Horn', 
    'Rapier Belt',
    'Raptor Skin',
    'Red Moko Grass', 
    'Red Rose', 
    'Red Round Table',
    'Red Terrapin', 
    'Rod',
    'Rolanberry', 
    'Ruddy Seema', 
    'Rusty Bucket',  
    'Rye Flour', 
    'Sage',
    'Sallet',
    'Salted Dfly. Trout',
    'san d\'Or. carrot',
    'San d\'Or. Flour', 
    'Scorpion Claw', 
    'Scorpion Shell', 
    'Semolina', 
    'Senroh Sardine',  
    'Shall Shell', 
    'Sheep Tooth', 
    'Skull Locust', 
    'Slime Juice',
    'Snapping Mole', 
    'Stone II',
    'Sunflower Seeds', 
    'Super Ether +1',
    'Sylvan Excursion',
    'Tarutaru Rice', 
    'Tiny Goldfish', 
    'Titanictus', 
    'Tourmaline Earring',
    'Turtle Shell',  
    'Ulbuconut', 
    'Ulbukan Lobster', 
    'Uragnite Shell', 
    'Vanilla',
    'Vegetable Soup',
    'Velkk Mask', 
    'Velkk Necklace', 
    'Vi. Sh. Leather',
    'Voay Staff -1', 
    'Voay Sword -1',
    'Walnut',  
    'Watermelon', 
    'Wijnruit', 
    'Wild Onion',
    'Win. Tea Leaves', 
    'Wivre Maul',
    'Woozyshroom', 
    'Yagudo Cherry', 
    'Yagudo Drink', 
    'Yayinbaligi', 
    'Yellow Jar',
    'Yorchete', 
    'Zebra Eel',
    'Zoni',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
	
			
    }

-- //sellnpc gems
profiles['gems'] = S{
    'Sunstone',
    'Aquamarine',
    'Sapphire',
    'Fluorite',
    'Spinel',
    'Jadeite',
    'Emerald',
    'Chrysoberyl',
    'Topaz',
    'Zircon',
    'Diamond',
    'Moonstone',
    'Tenebrite',
    'Fulmenite',
    'Larimar',
    'Selenite',
    'Tourmaline',
    }


return profiles








