-- Add items to existing profiles or create your own to sell groups of items using alias commands
local profiles = {}

-- //sellnpc powder
profiles['powder'] = S{
    'prize powder',
    }

-- //sellnpc ore
profiles['ore'] = S{
    'iron ore',
    'copper ore',
    'tin ore',
    }

-- //sellnpc junk
profiles['junk'] = S{
    'chestnut',
    'san d\'Or. carrot',
    }

-- //sellnpc alljunk
profiles['alljunk'] = S{
	
	'Garlic Cracker',
	'Konigskuchen',
	'Pogaca',
	'Roast Mushroom',
	'Soft-Boiled Egg',
	'san d\'Or. carrot',
	'Acheron Shield',
    'Acorn', 
    'Adoulinian Kelp', 
    'Aht Urhgan Dart',
    'Anchovy',
    'Antlion Jaw',  
    'Apkallu Feather',
    'Apple Juice',
    'Ardent Jadeite',
    'Barnacle', 
    'Bastore Bream', 
    'Bat Fang',  
    'Bay Leaves',
    'Beetle Jaw', 
    'Bhefhel Marlin',
    'Black Eel', 
    'Black Ghost', 
    'Black Pepper',
    'Black Prawn',  
    'Blk. Tiger Fang',  
    'Bloodblotch', 
    'Blue Peas', 
    'Bluetail', 
    'Bone Chip', 
    'Brass Harness',
    'Brass Loach', 
    'Bugard Tusk', 
    'Bull\'s Diary',
    'Ca Cuong', 
    'Cactus Stems', 
    'Carrier Crab Carapace',
    'Chestnut', 
    'Colibri Beak',
    'Cone Calamary', 
    'Contortopus', 
    'Cook. Kit 15',
    'Copper Frog', 
    'Coral Fungus', 
    'Cornstarch',
    'Crab Shell', 
    'Crawler Cocoon', 
    'Crawler Egg', 
    'Crayfish',  
    'Crescent Fish', 
    'Crying Mustard',
    'Dark Bass', 
    'Deathball',
    'Dhalmel Pie',
    'Dragon Bone', 
    'Dragon Fruit', 
    'Dragon Talon',  
    'Dragonfish', 
    'Dried Date',
    'Dried Date',
    'Dryad Root', 
    'Dwarf Remora', 
    'Eggplant',
    'Eggplant',  
    'El. Pachira Fruit', 
    'Elshimo Newt', 
    'Emperor Fish', 
    'Ether',
    'Faerie Apple',
    'Fish Bones',
    'Flax Flower', 
	'Flint Caviar',
    'Flint Stone', 
    'Fresh Marjoram', 
    'Fresh Mugwort', 
    'Frost Turnip',
    'Fruit Parfait',
    'Garglle. Shank',
    'Gavial Fish', 
    'Giant Catfish', 
    'Giant Stinger', 
    'Gigant Squid', 
    'Ginger',
    'Gold Carp', 
    'Green Rock', 
    'Grimmonite', 
    'Grove Cuttings', 
    'Gugru Tuna',  
    'H.Q. Crab Shell', 
    'H.Q. Scp. Shell', 
    'Habaneros',
    'Heart Chocolate',
    'Hi-Ether +2',
    'Igneous Rock', 
    'Infinity Core',
    'Insect Wing', 
    'Isleracea', 
    'Jack-o\'-Lantern',
    'Kazham Peppers',
    'King Locust', 
    'King Truffle',
    'Kukuru Bean', 
    'La Theine Cbg.', 
    'Land Crab Meat',
    'Leshonki Bulb',
    'Lesser Chigoe', 
    'Little Worm', 
    'Loc. Elutriator', 
    'Mackerel', 
    'Magnet Knife',
    'Maple Cake',
    'Marguerite', 
    'Matamata Shell',  
    'Matsya', 
    'Meteorite', 
    'Mhaura Garlic',
    'Millioncorn', 
    'Moat Carp', 
    'Moko Grass', 
    'Moorish Idol', 
    'Murex Spicule',
    'Mushrm. Locust',
    'Mushroom Salad',
    'Mushroom Soup',
    'Napa', 
    'Navarin',
    'Nopales', 
    'Orange Juice',
    'Pamamas', 
    'Peace Cape', 
    'Pebble Soup',
    'Pebble',  
    'Peeled Crayfish',
    'Peiste Skin',
    'Pepperoni Slice',
    'Pine Nuts', 
    'Pipira', 
    'Poison Flour', 
    'Popoto',
    'Potion +1',
    'Potion', 
    'Pro-Ether',
    'Puffball', 
    'Pugil Scales', 
    'Pukatrice Egg',
    'Pumpernickel',
    'Pumpkin Pie', 
    'Quus', 
    'R. Pickled R. Tail',
    'Ram Horn', 
    'Rapier Belt',
    'Raptor Skin',
    'Ratatouille',
    'Red Moko Grass', 
    'Red Rose', 
    'Red Round Table',
    'Red Terrapin', 
    'Roast Mutton',
    'Rod',
    'Rolanberry', 
    'Rotten Meat',
    'Ruddy Seema', 
    'Rusty Bucket',  
    'Rye Flour', 
    'Sage',
    'Sallet',
    'Salted Dfly. Trout',
    'San d\'Or. Flour', 
    'Scorpion Claw', 
    'Scorpion Shell', 
    'Semolina', 
    'Senroh Sardine',  
    'Shall Shell', 
    'Sheep Jerky',
    'Sheep Tooth', 
    'Skull Locust', 
    'Slime Juice',
    'Snapping Mole', 
    'Stone Cheese',
    'Stone II',
    'Sunflower Seeds', 
    'Super Ether +1',
    'Sylvan Excursion',
    'T. Timbers Salad',
    'Tarutaru Rice', 
    'Tiny Goldfish', 
    'Titanictus', 
    'Tourmaline Earring',
    'Turtle Shell',  
    'Ulbuconut', 
    'Ulbukan Lobster', 
    'Uragnite Shell', 
    'Vanilla',
    'Vegetable Soup',
    'Velkk Mask', 
    'Velkk Necklace', 
    'Vi. Sh. Leather',
    'Voay Staff -1', 
    'Voay Sword -1',
    'Wail. Bone Chip', 
    'Walnut',  
    'Watermelon', 
    'White Bread',
    'Wijnruit', 
    'Wild Onion',
    'Win. Tea Leaves', 
    'Wivre Maul',
    'Woozyshroom', 
    'Yagudo Cherry', 
    'Yagudo Drink', 
    'Yayinbaligi', 
    'Yayla Corbasi +1',
    'Yayla Corbasi',
    'Yellow Jar',
    'Yogurt Cake',
    'Yorchete', 
    'Zebra Eel',
    'Zoni',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
	
			
    }

-- //sellnpc gems
profiles['gems'] = S{
	'Amethyst',
	'Aquamarine',
	'Aventurine',
	'Chrysoberyl',
	'Clarite',
	'Diamond',
	'Emerald',
	'Fluorite',
	'Fulmenite',
	'Fulmenite',
	'Jadeite',
	'Lapis Lazuli',
	'Larimar',
	'Moonstone',
	'Painite', 
	'Sapphire',
	'Selenite',
	'Spinel',
	'Sunstone',
	'Tenebrite',
	'Topaz',
	'Tourmaline',
	'Zircon',
    }


return profiles








